numbers = {"pizza", "burger", "soup", "salad", "pasta"}
print("\nНижче виведеться список тричі\n")
print(numbers)
print(numbers)
print(numbers)
numbers.add("orange")
print("\nНижче додасться апельсинка\n")
print(numbers)
numbers.add("pizza")
print("\nТута зара буде ше піца\n")
print(numbers)
numbers.discard("burger")
print("\nА тута щас пропаде бургір(((\n")
print(numbers)
